[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/contracts/contract-1.pdf"
  to = "/contracts/contract-1.pdf"
  status = 200

[[redirects]]
  from = "/contracts-2.pdf"
  to = "/contracts-2.pdf"
  status = 200
